"""Ax/BoTorch Bayesian optimizer wrapper.

Wraps Ax ServiceAPI for a suggest/update loop with optional causal guidance
via focus variables (POMIS/screening integration) and POMIS priors.

Graceful degradation: if ``ax`` is not installed, instantiating
``AxBayesianOptimizer`` raises an ``ImportError`` with a clear install hint.
"""

from __future__ import annotations

import logging
from typing import Any

from causal_optimizer.types import SearchSpace, VariableType

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Availability check — runs at module import time so the error is surfaced
# as early as possible (constructor call) rather than at first suggest().
# ---------------------------------------------------------------------------

try:
    from ax.service.ax_client import AxClient
    from ax.service.utils.instantiation import ObjectiveProperties

    _AX_AVAILABLE = True
except ImportError:
    _AX_AVAILABLE = False


class AxBayesianOptimizer:
    """Wraps Ax ServiceAPI for suggest/update loop.

    Parameters
    ----------
    search_space:
        The optimization search space.
    objective_name:
        Name of the metric to optimize.
    minimize:
        Whether to minimize (True) or maximize (False) the objective.
    focus_variables:
        If provided, only these variables are optimized by Ax; others are
        fixed at their midpoint value.
    pomis_prior:
        When set, candidates that only touch POMIS variables receive a soft
        bonus: non-POMIS variables are fixed at midpoint (equivalent to
        treating the candidate as POMIS-only).  Implemented as a post-hoc
        filter — 80% of the time a POMIS-only suggestion is returned,
        20% a full-space suggestion.
    seed:
        Random seed forwarded to ``AxClient`` for reproducibility.

    Raises
    ------
    ImportError
        If ``ax-platform`` is not installed.  Install with
        ``uv sync --extra bayesian``.
    """

    def __init__(
        self,
        search_space: SearchSpace,
        objective_name: str,
        minimize: bool = True,
        focus_variables: list[str] | None = None,
        pomis_prior: list[frozenset[str]] | None = None,
        seed: int | None = None,
    ) -> None:
        if not _AX_AVAILABLE:
            raise ImportError(
                "ax-platform is required for AxBayesianOptimizer. "
                "Install it with: uv sync --extra bayesian"
            )

        self._search_space = search_space
        self._objective_name = objective_name
        self._minimize = minimize
        self._focus_variables: list[str] = focus_variables or []
        self._pomis_prior = pomis_prior or []
        self._seed = seed

        # Determine which variables are "active" (varied by Ax) vs "fixed" (held at midpoint)
        focus_set = set(self._focus_variables) if self._focus_variables else None

        self._active_vars = [
            v for v in search_space.variables if focus_set is None or v.name in focus_set
        ]
        self._fixed_vars = [
            v for v in search_space.variables if focus_set is not None and v.name not in focus_set
        ]

        # Pre-compute midpoints for fixed variables and POMIS non-focus variables
        self._midpoints: dict[str, Any] = {}
        for var in self._fixed_vars:
            self._midpoints[var.name] = self._midpoint_for(var)

        if self._pomis_prior:
            pomis_union: set[str] = set()
            for s in self._pomis_prior:
                pomis_union |= s
            for var in search_space.variables:
                if var.name not in pomis_union and var.name not in self._midpoints:
                    self._midpoints[var.name] = self._midpoint_for(var)

        # Build the Ax parameter defs for active variables only
        ax_params = self._build_ax_params()
        if not ax_params:
            # Nothing to optimise — reset to all variables
            self._active_vars = list(search_space.variables)
            self._fixed_vars = []
            ax_params = self._build_ax_params()

        # Initialise AxClient
        # enforce_sequential_optimization=False: allows get_next_trial() even when
        # there are attach_trial()-sourced observations that weren't generated by Ax
        # (historical data pre-loading).  Without this flag, Ax raises DataRequiredError
        # when it tries to transition from Sobol to BoTorch but finds that the "generated"
        # trial count is below the MinTrials threshold (because the historical trials
        # were attached, not generated).
        client_kwargs: dict[str, Any] = {
            "verbose_logging": False,
            "enforce_sequential_optimization": False,
        }
        if seed is not None:
            client_kwargs["random_seed"] = seed

        self._client: AxClient = AxClient(**client_kwargs)
        self._client.create_experiment(
            name="causal_optimizer",
            parameters=ax_params,
            objectives={objective_name: ObjectiveProperties(minimize=minimize)},
        )

        # Pending trial state: when suggest() is called, a trial is left RUNNING
        # until update() completes it or the next suggest() abandons it.
        self._pending_trial_idx: int | None = None
        self._pending_full_params: dict[str, Any] = {}

        # Track observations for best() lookup
        self._observations: list[tuple[dict[str, Any], float]] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def suggest(self) -> dict[str, Any]:
        """Generate the next candidate parameter dict.

        If a pending trial exists from a previous ``suggest()`` call that was
        never updated, it is abandoned before generating a new trial.

        If ``pomis_prior`` is set, with 80% probability the non-POMIS variables
        are clamped to their midpoints so the suggestion targets POMIS variables
        only.
        """
        import random

        # Abandon any un-updated pending trial from a previous suggest() call
        if self._pending_trial_idx is not None:
            self._client.abandon_trial(
                trial_index=self._pending_trial_idx,
                reason="superseded by new suggest() call",
            )
            self._pending_trial_idx = None

        active_params, trial_idx = self._client.get_next_trial()
        self._pending_trial_idx = trial_idx

        result: dict[str, Any] = dict(active_params)

        # Fill fixed variables at midpoint
        for var in self._fixed_vars:
            result[var.name] = self._midpoints[var.name]

        # Apply POMIS prior with 80% probability
        if self._pomis_prior:
            if random.random() < 0.8:  # noqa: S311
                pomis_union: set[str] = set()
                for s in self._pomis_prior:
                    pomis_union |= s
                for var in self._search_space.variables:
                    if var.name not in pomis_union and var.name in self._midpoints:
                        result[var.name] = self._midpoints[var.name]

        self._pending_full_params = dict(result)
        return result

    def update(self, params: dict[str, Any], value: float) -> None:
        """Feed an observed (params, value) pair back to the optimizer.

        If the last ``suggest()`` trial is still pending, it is completed with
        the given value.  Otherwise, the observation is attached as a new trial
        and immediately completed (historical data loading).

        Only the active-variable subset of ``params`` is forwarded to Ax.
        """
        active_names = {v.name for v in self._active_vars}
        active_params = {k: v for k, v in params.items() if k in active_names}

        if self._pending_trial_idx is not None:
            # Complete the pending trial that was generated by suggest()
            self._client.complete_trial(
                trial_index=self._pending_trial_idx,
                raw_data={self._objective_name: value},
            )
            self._pending_trial_idx = None
        else:
            # Pre-load historical observation: attach a new trial and complete immediately
            _, trial_idx = self._client.attach_trial(active_params)
            self._client.complete_trial(
                trial_index=trial_idx,
                raw_data={self._objective_name: value},
            )

        self._observations.append((dict(params), value))

    def best(self) -> dict[str, Any] | None:
        """Return the best observed parameter dict, or None if no observations yet."""
        if not self._observations:
            return None

        if self._minimize:
            best_params, _ = min(self._observations, key=lambda x: x[1])
        else:
            best_params, _ = max(self._observations, key=lambda x: x[1])
        return dict(best_params)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _build_ax_params(self) -> list[dict[str, Any]]:
        """Build the Ax parameter specification list from active variables."""
        ax_params: list[dict[str, Any]] = []
        for var in self._active_vars:
            if var.variable_type == VariableType.CONTINUOUS:
                ax_params.append(
                    {
                        "name": var.name,
                        "type": "range",
                        "bounds": [var.lower or 0.0, var.upper or 1.0],
                        "value_type": "float",
                    }
                )
            elif var.variable_type == VariableType.INTEGER:
                ax_params.append(
                    {
                        "name": var.name,
                        "type": "range",
                        "bounds": [int(var.lower or 0), int(var.upper or 10)],
                        "value_type": "int",
                    }
                )
            elif var.variable_type == VariableType.CATEGORICAL and var.choices:
                ax_params.append(
                    {
                        "name": var.name,
                        "type": "choice",
                        "values": list(var.choices),
                        "is_ordered": False,
                    }
                )
            elif var.variable_type == VariableType.BOOLEAN:
                # Represent booleans as a FLOAT [0, 1] range; caller rounds as needed
                ax_params.append(
                    {
                        "name": var.name,
                        "type": "range",
                        "bounds": [0.0, 1.0],
                        "value_type": "float",
                    }
                )
        return ax_params

    @staticmethod
    def _midpoint_for(var: Any) -> Any:
        """Compute the midpoint (default value) for a variable."""
        vt = var.variable_type
        if vt == VariableType.CONTINUOUS:
            lo = var.lower if var.lower is not None else 0.0
            hi = var.upper if var.upper is not None else 1.0
            return (lo + hi) / 2.0
        if vt == VariableType.INTEGER:
            lo = int(var.lower) if var.lower is not None else 0
            hi = int(var.upper) if var.upper is not None else 10
            return (lo + hi) // 2
        if vt == VariableType.BOOLEAN:
            return False
        if vt == VariableType.CATEGORICAL and var.choices:
            return var.choices[len(var.choices) // 2]
        return None
